version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.1-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install JRE for Sonar scanner
          command: sudo apt install openjdk-8-jre

#      - run:
#          name: Deinstall current Firefox and install Firefox 55.0
#          command: |
#            sudo apt-get purge -y firefox
#            wget https://sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_55.0.1-0ubuntu1_amd64.deb
#            sudo dpkg -i firefox-mozilla-build_55.0.1-0ubuntu1_amd64.deb

      - run:
          name: Print node, npm and yarn versions
          command: node -v && npm -v && yarn -v

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install web page dependencies
          command: yarn install

      - run:
          name: Install functions dependencies
          command: cd functions && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Analyze with Sonar scanner
          command: sh ./node_modules/sonar-scanner/bin/sonar-scanner -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.host.url=$SONARQUBE_URL

      - run:
          name: Build application
          command: yarn run build

      - run:
          name: Start application
          command: yarn start
          background: true

      - run:
          name: Start Selenium
          command: java -jar node_modules/selenium-server/lib/runner/selenium-server-standalone-3.141.59.jar -log src/test/acceptance/selenium.log
          background: true

      - run: sleep 10

      - run:
          name: Run E2E tests
          command: yarn run nightwatch

      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project=lamas-85831
